# Add configuration values here, as shown below.
#
    nutritionix_app_id: "7d1a796f"
    nutritionix_app_key: "c751cd5e7aaf33dc5487cd28bb6fbd09"

    gmail_username: "codediode23@gmail.com"
    gmail_password: "186Diamondroof65"

    google_storage_access_key_id: "GOOGQVECU7LBM7PLEOEM"
    google_storage_secret_access_key: "pdUpxF9H8Qif4K/QmGEObtg2BgLx5eGawT1qvpxe"

# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
